Umweltzone/src/main/java/de/avpptr/umweltzone/analytics/GoogleAnalyticsTracking.java
Set custom ExceptionParser in Google Analytics ExceptionReporter in
order to include the stack trace of uncaught exceptions in the tracking
message. This is for Google Analytics v2.
=> Use custom ExceptionParser when using GoogleAnalyticsTracking

Umweltzone/src/main/java/de/avpptr/umweltzone/zones/ZonesAdapter.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/zones/viewholders/OneZoneViewHolder.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/zones/viewholders/TwoZonesViewHolder.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/zones/viewholders/ZoneViewHolder.kt
Following our Slack conversation. I took a look at the code, and I did a couple of changes.
This is what I usually do when using sealed classes together with ViewHolders on RecyclerView Adapters. I am not sure if it is the best solution.
The advantage is getting rid of the `when` case in `onBindViewHolder`.
The disadvantage is the `UNCHECKED_CAST` in `onCreateViewHolder`. It is what annoys me most. Maybe this can be improved but I could not figure it out.
But what I like most is having an abstract `bind` method that all future ViewHolders have to implement, including adding a new sealed class child.
Let me know what you think!
=> Idea to use sealed classes on ViewHolders

Umweltzone/src/main/java/de/avpptr/umweltzone/contract/Preferences.java, Umweltzone/src/main/java/de/avpptr/umweltzone/map/MapFragment.java, Umweltzone/src/main/java/de/avpptr/umweltzone/map/MapReadyDelegate.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/models/extensions/CameraPositionExtensions.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/models/extensions/LatLngExtensions.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/models/extensions/LatitudeExtensions.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/models/extensions/LongitudeExtensions.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/prefs/CameraPositionPreference.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/prefs/PreferencesHelper.java, Umweltzone/src/main/java/de/avpptr/umweltzone/utils/GeoPoint.java, Umweltzone/src/test/java/de/avpptr/umweltzone/models/extensions/CameraPositionExtensionsTest.kt, Umweltzone/src/test/java/de/avpptr/umweltzone/models/extensions/LatitudeExtensionsTest.kt, Umweltzone/src/test/java/de/avpptr/umweltzone/models/extensions/LongitudeExtensionsTest.kt
+ Store and restore "tilt" angle and "bearing" of the map camera position.
Before only "target" location and "zoom" level have been kept.
- Map before rotation
- Map after rotation
- Successfully tested on Nexus 9, Android 7.1.1.
Resolves #20.
=> Completely restore the map view on rotation as chosen by the user.

README.md, Umweltzone/src/main/res/values/strings.xml, Umweltzone/src/main/res/xml/settings.xml, openstreetmap-taginfo/taginfo.json
- The project repository has moved from `https://github.com/johnjohndoe/Umweltzone` to `https://github.com/Umweltzone/Umweltzone`.
- Any access to the former URL is automatically redirected. Nevertheless, URLs are updated here.
=> Update URLs to reflect the new project location.

Umweltzone/src/main/res/layout/settings_item.xml, Umweltzone/src/main/res/values/styles.xml, Umweltzone/src/main/res/xml/settings.xml
+ `SwitchPreference` is available since API level 14 and can be used now
because the `minSdkVersion` was raised in b0982e2472e8250383f6938a6f738baf7cd766be.
+ The custom layout is still needed for correct rendering on devices with
older Android versions.
+ Related commit: 41e89910649bb6a34b649510ba6421a70508c0b0.
- The Settings screen with a checkbox.
- The Settings screen with a switch.
- Google Pixel 2, Android 10
- LG Nexus 5, Android 6.0.1
- Motorola Moto G, Android 5.1
Resolves #32.
=> Use SwitchPreference instead of CheckBoxPreference.

README.md, Umweltzone/src/main/java/de/avpptr/umweltzone/feedback/FeedbackActivity.java, Umweltzone/src/main/res/layout/appinfo_feedback.xml, Umweltzone/src/main/res/values-de/strings.xml, Umweltzone/src/main/res/values/strings.xml
+ Removes the _UserVoice_ section from the _Feedback_ screen.
+ Updates the feedback secion in the README.
+ Users did rarely use the service.
Resolves #37
=> RIP UserVoice.

build.gradle
+ Error: `NoClassDefFoundError: java.util.Objects`.
+ Revert version update done in: db1173da74c2b7c1e296a612af88faf9bb281dc4.
+ Related: https://github.com/FasterXML/jackson-databind/issues/2599.
- :heavy_check_mark: Android emulator, Nexus 5, Android 4.3.1 (API level 18, Jelly Bean), Intel x86 Atom, `system-images;android-18;google_apis;x86`, revision: 6.
Resolves #50.
=> Prevent crash on Android 4.1.x - 4.3.x caused by jackson-databind.

Umweltzone/src/androidTest/java/de/avpptr/umweltzone/about/AboutActivityTest.java, Umweltzone/src/androidTest/java/de/avpptr/umweltzone/details/DetailsFragmentTest.kt, Umweltzone/src/androidTest/java/de/avpptr/umweltzone/details/DieselProhibitionsZoneDetailsFragmentTest.kt, Umweltzone/src/androidTest/java/de/avpptr/umweltzone/details/NoCitySelectedFragmentTest.kt, Umweltzone/src/androidTest/java/de/avpptr/umweltzone/utils/ContentProviderTest.java
+ Broken since AndroidX migration: 0fdc1af5606cccfeee4b3597a8dcff5f084ec067.
+ Error: `java.lang.RuntimeException: Could not launch activity` ... `android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`
- LG Nexus 5 (Android 6.0.1, API 23)
- HTC Nexus 9 (Android 7.1.1, API 25)
- Google Pixel 2 (Android 10, API 29)
Co-authored-by: @cketti
=> Fix instrumentation tests which launch an Activity.

Umweltzone/build.gradle, Umweltzone/src/main/java/de/avpptr/umweltzone/Umweltzone.java, Umweltzone/src/main/java/de/avpptr/umweltzone/map/MainActivity.java, Umweltzone/src/main/java/de/avpptr/umweltzone/map/ZoneNotDrawableDialog.java, Umweltzone/src/main/java/de/avpptr/umweltzone/utils/StringHelper.java
- `compileSdkVersion 29`
- `targetSdkVersion 29`
- Replace deprecated `android.preference.PreferenceManager` with `androidx.preference.PreferenceManager`.
- Use new `Activity#setShowWhenLocked` method to show map on lock screen.
- Replace deprecated `Html#fromHtml` with `HtmlCompat#fromHtml`.
- Fresh installation
- Installation update
- Check "Settings" screen rendering.
- Check lock screen feature.
- Unit tests
- Instrumentation tests (on Travis CI and HTC Nexus 9, Android 7.1.1)
- Google Pixel 2, Android 10, API 29.
- HTC Nexus 9, Android 7.1.1, API 25.
- Emulator 4.1.2, API 16, w/o Google Play Services.
Resolves #56.
=> SDK 29 updates

Umweltzone/src/main/res/values-da/strings.xml, Umweltzone/src/main/res/values-de/strings.xml, Umweltzone/src/main/res/values-nl/strings.xml, Umweltzone/src/main/res/values-pl/strings.xml, Umweltzone/src/main/res/values/strings.xml
- Always use "https" in web links.
- Except _Parceler_ which still serves via "http".
- Fix broken URLs pointing to used software libraries.
=> Links housekeeping

Umweltzone/src/main/java/de/avpptr/umweltzone/base/BaseActivity.java, Umweltzone/src/main/res/values-de/ckchangelog.xml, Umweltzone/src/main/res/values/ckchangelog.xml
+ Show toast message and skip opening version information.
+ See: https://github.com/cketti/ckChangeLog/issues/57.
+ Workaround to be removed once AppCompat 1.2.0 is published and fixes the bug.
=> Prevent crash caused by AppCompat 1.1.0 on Android 5.0.2.

Umweltzone/src/main/AndroidManifest.xml
+ Related commit: 06170d6cee5e29f928469d07df87f9913a14459c.
+ Release build successfully tested on:
- Google Pixel 2 device, Android 10 (API 29)
=> Remove by now unneeded minSdkVersion override for Support Library 23.4.0.

Umweltzone/build.gradle, Umweltzone/src/main/AndroidManifest.xml, Umweltzone/src/main/java/de/avpptr/umweltzone/about/AboutActivity.java, Umweltzone/src/main/java/de/avpptr/umweltzone/utils/LinkMovementMethodCompat.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/utils/ViewHelper.java, Umweltzone/src/main/res/color/button_web_text_color_link.xml, Umweltzone/src/main/res/color/email_text_color_link.xml, Umweltzone/src/main/res/layout/appinfo_libraries.xml, Umweltzone/src/main/res/values/colors.xml, Umweltzone/src/main/res/values/strings.xml, Umweltzone/src/main/res/values/styles.xml
+ Affected screens:
- Details
- FAQs
- Feedback
- About
+ Use [`better-link-movement-method:2.2.0`](https://github.com/saket/Better-Link-Movement-Method) on devices running Android 4.1.x or newer. On devices running an older Android version links are not enhanced.
+ Prepending `mailto:` to the feedback email address is no longer needed for newer devices as it would otherwise cause the string being present in the user's email client.
with `release` build
- Google Pixel 2 device, Android 10 (API 29)
- Nexus 5X emulator, Android 4.1.2 (API 16)
- Nexus 5X emulator, Android 4.0.3 (API 15)
=> Enhance visual touch feedback of links of all kinds.

Umweltzone/src/main/res/values-da/strings.xml, Umweltzone/src/main/res/values-de/strings.xml, Umweltzone/src/main/res/values-nl/strings.xml, Umweltzone/src/main/res/values-pl/strings.xml, Umweltzone/src/main/res/values/strings.xml
- This fixes a crash which occurred when a user with her device **language set to Netherlands** selects a city (Regensburg, Wiesbaden) which has **no zone data** to draw attached to it. Due to the **malformed dialog and email text** the app crashed with an `UnknownFormatConversionException`, see stacktrace. The bug was introduced in PR #43.
- Fix **missing German email text part** for devices with the language set to Netherlands.
- Improve formatting (remove unneeded **whitespace**) of "zone not drawable" texts for devices with the language set to Netherlands.
- Add **missing empty line** in email texts for devices with the language set to Danish, Polish or English.
- Change separator in email subject text.
``` java
java.util.UnknownFormatConversionException: 
at …
```
=> Zone not drawable bugfixes

Umweltzone/build.gradle, Umweltzone/src/main/java/de/avpptr/umweltzone/about/AboutActivity.java
+ This reduces the number of task which rerun from 8 to 4. If the consecutive build happens within the same minute no task reruns.
Thanks to @runningcode for coming up with the idea!
---
Related IDE issue: https://issuetracker.google.com/issues/159363771.
=> Decrease build time.

.travis.yml
+ The [Android Gradle Plugin v.7.0.0](https://developer.android.com/studio/releases/gradle-plugin#7-0-0) requires JDK 11 - therefore also Travis CI must be able to run the build in such an environment.
+ Download [command line tools](https://developer.android.com/studio/command-line/) ourselves instead of relying on Android SDK being preinstalled in the Travis CI image.
+ Read `targetSdkVersion` and `buildToolsVersion` from project setup to reduce maintenance.
+ Configure caching for Travis CI.
=> Update Travis CI configuration to prepare running with JDK 11.

Umweltzone/src/main/java/de/avpptr/umweltzone/base/BaseActivity.java, Umweltzone/src/main/java/de/avpptr/umweltzone/utils/IntentHelper.java
+ The system UI handles the case of no matching apps.
+ Inspired by https://github.com/EventFahrplan/EventFahrplan/pull/309 by @cketti.
- Google Pixel 2 device, Android 11 (API 30)
=> Use system's share UI when sharing the app.

Umweltzone/build.gradle, Umweltzone/src/main/java/de/avpptr/umweltzone/zones/ZonesAdapter.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/zones/ZonesFragment.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/zones/viewholders/OneZoneViewHolder.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/zones/viewholders/ThreeZonesViewHolder.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/zones/viewholders/TwoZonesViewHolder.kt
kotlin-android-extensions has been deprecated in favor of view binding. Replace synthetics usage with view binding.
Closes #126
=> Replace Kotlin synthetics with view binding

Umweltzone/build.gradle, Umweltzone/src/main/AndroidManifest.xml, Umweltzone/src/main/java/de/avpptr/umweltzone/details/DetailsActivity.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/details/DetailsFragment.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/extensions/ParcelableCompat.kt, Umweltzone/src/main/java/de/avpptr/umweltzone/map/ZoneNotDrawableDialog.java, Umweltzone/src/main/res/xml/locales_config.xml, build.gradle
+ Use targetSdk 33 and compileSdk 33 (Android 13).
+ Support [per-app language preferences](https://developer.android.com/about/versions/13/features/app-languages).
+ Use androidx.core:core-ktx:1.9.0.
+ Document `lifecycle-viewmodel-ktx` build error.
- Samsung Galaxy Tab S7 FE device, Android 13 (API 33)
- Google Pixel 6 device, Android 13 (API 33)
=> Update project setup (SDK 33, per-app language preferences)

Umweltzone/build.gradle, Umweltzone/src/main/AndroidManifest.xml
+ https://developer.android.com/studio/build/configure-app-module#set-namespace
+ https://developer.android.com/studio/releases/gradle-plugin#package-deprecated
- Samsung Galaxy Tab S7 FE device, Android 13 (API 33)
=> Replace deprecated "package" attribute with "namespace" declaration.
